### ISSUE TITLE
error when clicking lecture discussion in lecture page

### ISSUE THREAD

**Issue by drouba** [jamestjw/comp5531-w22-proj#101]
![image](https://user-images.githubusercontent.com/79241726/164802840-01ccac05-eea2-43cc-9e2a-e44e98403a65.png)
to recreate
- login as a afinch@mail.com
- go to lecture BB page
- go to discussion page of lecture BB
- create a new discussion
- log out
- log in as bdesai@concordia.ca
- go to lecutre BB page
- go to discussion page of lecture BB
- click on the discussion link

**Comment by jamestjw** [comment]
Ok this is fixed
