### ISSUE TITLE
Invalid username or password persistent notification

### ISSUE THREAD

**Issue by chris7neves** [jamestjw/comp5531-w22-proj#34]
* Enter an invalid username or password
* "Invalid username or password!" warning appears at the top of the page
* Enter the correct login information
* Invalid username or password message stays at the top of the page, even after refreshing and navigating to a different page.

**Comment by jamestjw** [comment]
Yeah this is an annoying problem 😂 Storing an error message in the Session object turned out to be a bad idea, since it doesn't get cleared even after the message is showed once. I guess we'll have to find a better way of doin this

**Comment by jamestjw** [comment]
https://github.com/jamestjw/comp5531-w22-proj/pull/43 fixed here I think
