### ISSUE TITLE
After adding a course offering, "No offering found. Add a course offering" message appears in Sections

### ISSUE THREAD

**Issue by chris7neves** [jamestjw/comp5531-w22-proj#35]
* Sign in as admin
* add a course
* add an offering
* Under section, "No offering found. Add a course offering:" message appears even if course offering is added

**Comment by Zachary-Concordia** [comment]
I believe this one is resolved in the rename - I can't replicate it

**Comment by drouba** [comment]
checked it out, problem is resolved
