### ISSUE TITLE
assigning instructors to lectures should not be based on ID and the dropdown should contain more description

### ISSUE THREAD

**Issue by chris7neves** [jamestjw/comp5531-w22-proj#54]
![image](https://user-images.githubusercontent.com/38571540/164040605-5d5492d7-0619-4ba1-97ea-062e127f716d.png)

**Comment by jamestjw** [comment]
ok lets make it show the Lecture code then? that should be sufficient ?

**Comment by drouba** [comment]
DONE fix is in new pr branch is called issue_54_fix
