### ISSUE TITLE
assigning an instructor to a lecture yields a undefined property warning that appears momentarily

### ISSUE THREAD

**Issue by chris7neves** [jamestjw/comp5531-w22-proj#55]
![image](https://user-images.githubusercontent.com/38571540/164041126-8bfc5677-3f7f-484b-bc98-ae63dace7ce7.png)

**Comment by jamestjw** [comment]
I think the fix is in one of @drouba 's branches https://github.com/jamestjw/comp5531-w22-proj/pull/51

**Comment by drouba** [comment]
yup, fix is on #51

**Comment by drouba** [comment]
fixed
