### ISSUE TITLE
meetings not displayed in meeting page after being created

### ISSUE THREAD

**Issue by chris7neves** [jamestjw/comp5531-w22-proj#61]
![image](https://user-images.githubusercontent.com/38571540/164083516-1ce4ffaf-d4bf-4f9d-aa5f-1f9421ba2a66.png)

![image](https://user-images.githubusercontent.com/38571540/164083591-5fb8ea49-7129-487f-b699-3e7e97cfa243.png)

![image](https://user-images.githubusercontent.com/38571540/164083634-19583911-23ef-4bd4-be88-fa6c377afbb2.png)

**Comment by drouba** [comment]
gonna have a look at this one

**Comment by jamestjw** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/44499264/164131856-18a2cb28-109a-4aaf-9353-8da3600abfcc.png">
 can't reproduce in `main `
