### ISSUE TITLE
Invalid access message appears when users other than admin go to the annoucements page

### ISSUE THREAD

**Issue by drouba** [jamestjw/comp5531-w22-proj#70]
![image](https://user-images.githubusercontent.com/79241726/164279717-68021c25-f285-433b-835d-7a5db87f71e8.png)

Steps to recreate:
- login as student
- go to announcements page

**Comment by jamestjw** [comment]
@drouba i think we resolved this ?

**Comment by drouba** [comment]
yeah we did, I'll double check

**Comment by drouba** [comment]
yup resolved
